"""One-call functions over the pure-python engine

Docs: https://AnswerDotAI.github.io/fastanki/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_core.ipynb.

# %% auto #0
__all__ = ['add_card', 'add_fb_card', 'add_cloze_card', 'add_media', 'find_notes', 'find_note_ids', 'find_cards', 'find_card_ids',
           'get_note', 'update_note', 'update_fb_note', 'del_note', 'sync', 'anki_tools']

# %% ../nbs/03_core.ipynb #3d1b9c61
from fastcore.utils import *
from .schema import *
from .collection import *
from .syncer import *
from .media import *

# %% ../nbs/03_core.ipynb #eec56ce5
def add_card(
    model:str='Basic', # Notetype name (the tool description lists each notetype's fields)
    deck:str='Default', # Deck name (`::` for nesting; created if needed)
    tags:str=None, # Space-separated tags
    fields:dict=None, # Field name -> value, e.g. {'Front':'2+2', 'Back':'4'}
):
    "Add a card of any notetype, returning the new note id. Field names must match the notetype."
    with Collection.open() as col:
        return col.add(model=model, deck=deck, tags=tags.split() if tags else None, **(fields or {})).id

def add_fb_card(
    front:str, # Front (question) text
    back:str, # Back (answer) text
    deck:str='Default', # Deck name (`::` for nesting; created if needed)
    tags:str=None, # Space-separated tags
):
    "Add a Basic card, returning the new note id."
    return add_card(deck=deck, tags=tags, fields={'Front':front, 'Back':back})

def add_cloze_card(
    text:str, # Cloze text with `{{c1::hidden}}` deletions
    back_extra:str='', # Extra info shown on the back of every card
    deck:str='Default', # Deck name (`::` for nesting; created if needed)
    tags:str=None, # Space-separated tags
):
    "Add a Cloze card (`{{c1::hidden}}` syntax), returning the new note id."
    return add_card(model='Cloze', deck=deck, tags=tags, fields={'Text':text, 'Back Extra':back_extra})

# %% ../nbs/03_core.ipynb #1297f63f
def add_media(
    path:str, # File to copy into the collection's media folder
    fname:str=None, # Name to store it under (default: the file's own name)
):
    "Add a media file to the collection, returning the filename to cite in fields: <img src=\"name\"> or [sound:name]."
    with Collection.open() as col: return col.add_media(path, fname)

# %% ../nbs/03_core.ipynb #000f044d
def find_notes(deck:str=None, # Deck name (matches subdecks too)
               tag:str=None, # Tag to match
               added_days:int=None, # Only notes added in the last this-many days
               fields:dict=None): # Field name -> case-insensitive substring, e.g. {'Front':'hello'}
    "Notes matching all given criteria."
    with Collection.open() as col: return col.find_notes(deck=deck, tag=tag, added_days=added_days, **(fields or {}))

def find_note_ids(deck:str=None, # Deck name (matches subdecks too)
                  tag:str=None, # Tag to match
                  added_days:int=None, # Only notes added in the last this-many days
                  fields:dict=None): # Field name -> case-insensitive substring, e.g. {'Front':'hello'}
    "Ids of notes matching all given criteria."
    return [n.id for n in find_notes(deck=deck, tag=tag, added_days=added_days, fields=fields)]

# %% ../nbs/03_core.ipynb #d1ddb102
def find_cards(deck:str=None, # Deck name (matches subdecks too)
               tag:str=None, # Tag to match
               added_days:int=None, # Only cards added in the last this-many days
               is_due:bool=None, # Only cards due for review
               fields:dict=None): # Field name -> case-insensitive substring, e.g. {'Front':'hello'}
    "Cards matching all given criteria."
    with Collection.open() as col: return col.find_cards(deck=deck, tag=tag, added_days=added_days, is_due=is_due, **(fields or {}))

def find_card_ids(deck:str=None, # Deck name (matches subdecks too)
                  tag:str=None, # Tag to match
                  added_days:int=None, # Only cards added in the last this-many days
                  is_due:bool=None, # Only cards due for review
                  fields:dict=None): # Field name -> case-insensitive substring, e.g. {'Front':'hello'}
    "Ids of cards matching all given criteria."
    return [c.id for c in find_cards(deck=deck, tag=tag, added_days=added_days, is_due=is_due, fields=fields)]

# %% ../nbs/03_core.ipynb #ed586b1b
def get_note(
    note_id:int, # Id of the note to retrieve
):
    "Retrieve a note by id."
    with Collection.open() as col: return col.get_note(note_id)

# %% ../nbs/03_core.ipynb #c24dadf8
def update_note(note, tags=None, add_tags=None, **fields):
    "Update fields and/or tags of a `Note` or note id; `tags` replaces, `add_tags` appends."
    with Collection.open() as col: return col.update_note(note, tags=tags, add_tags=add_tags, **fields)

def update_fb_note(
    note_id:int, # Id of the Basic note to update
    front:str='', # New Front text (empty leaves it unchanged)
    back:str='', # New Back text (empty leaves it unchanged)
    tags:str=None, # Space-separated tags, replacing all existing tags
    add_tags:str=None, # Space-separated tags to add, keeping existing ones
):
    "Update a Basic note's front/back and/or tags."
    kw = {}
    if front: kw['Front'] = front
    if back: kw['Back'] = back
    if tags: tags = tags.split()
    if add_tags: add_tags = add_tags.split()
    return update_note(note_id, tags=tags, add_tags=add_tags, **kw)

def del_note(
    notes:list, # Note ids (or `Note` objects) to delete, along with their cards
):
    "Delete note(s) (and their cards) by `Note` or id, singly or in a list."
    with Collection.open() as col: return col.remove_notes(notes)

# %% ../nbs/03_core.ipynb #5f330861
def sync(
    user:str=None, # AnkiWeb email (only needed the first time)
    passw:str=None, # AnkiWeb password (only the first time; a host key is saved after)
    endpoint:str=None, # Sync server URL (defaults to AnkiWeb)
    upload:bool=False, # Force-upload the local collection, replacing the server copy
    media:bool=True, # Also sync media files
):
    "Sync the default collection with AnkiWeb. Pass credentials the first time; they're saved after that."
    with Collection.open() as col:
        res = col.sync(user=user, passw=passw, endpoint=endpoint, upload=upload)
        if media: col.sync_media()
        return res

# %% ../nbs/03_core.ipynb #6ab4881e
def anki_tools(): print('&`[add_card, add_fb_card, add_cloze_card, add_media, find_notes, find_note_ids, find_cards, find_card_ids, get_note, del_note, update_fb_note, sync]`')
