"""Media files and the AnkiWeb media sync protocol

Docs: https://AnswerDotAI.github.io/fastanki/media.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_media.ipynb.

# %% auto #0
__all__ = ['MAX_FNAME_BYTES', 'MEDIA_SCHEMA', 'MAX_FILE_SIZE', 'MAX_ZIP_FILES', 'TARGET_ZIP_BYTES', 'norm_fname',
           'add_media_file', 'Media', 'MediaSanityFailed', 'required_change']

# %% ../nbs/04_media.ipynb #690d8db4
import zipfile, io, hashlib, unicodedata, json
from fastcore.utils import *
from .schema import *
from .collection import *
from .syncer import *

# %% ../nbs/04_media.ipynb #08bccd3e
MAX_FNAME_BYTES = 120
_WIN_DEVICE = re.compile(r'(?i)^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\.|$)')
_NONSYNCABLE = re.compile(r'(?i)^(thumbs\.db|\.ds_store)$')

def _disallowed(c): return c in '[]<>:"/?*^\\|' or c<='\x1f' or c=='\x7f' or unicodedata.category(c)=='Cn'

def _trunc_bytes(s, n):
    "Truncate `s` to at most `n` utf-8 bytes, on a character boundary"
    while len(s.encode())>n: s = s[:-1]
    return s

def _stem_ext(fname, max_bytes):
    "Split into (stem, ext), each truncated so the joined name fits `max_bytes` (ext capped at 10 bytes)"
    stem,dot,ext = fname.rpartition('.')
    if not dot: stem,ext = ext,''
    ext = _trunc_bytes(ext, 10)
    return _trunc_bytes(stem, max_bytes-len(ext.encode())-2), ext

def norm_fname(fname):
    "Normalize a media filename as Anki does: NFC, problem characters stripped, device names defused, 120 bytes max"
    fname = unicodedata.normalize('NFC', fname)
    fname = ''.join(c for c in fname if not _disallowed(c)).replace('\xa0', ' ')
    fname = _WIN_DEVICE.sub(r'\1_\2', fname)
    if len(fname.encode())>MAX_FNAME_BYTES:
        stem,ext = _stem_ext(fname, MAX_FNAME_BYTES)
        fname = f'{stem}.{ext}' if ext else stem
    if fname.endswith((' ', '.')): fname += '_'
    return fname

def _hash_name(fname, csum):
    "foo.jpg -> foo-{csum}.jpg, for renaming a file whose name is taken by different content"
    stem,ext = _stem_ext(fname, MAX_FNAME_BYTES-41)
    return f'{stem}-{csum}.{ext}'

# %% ../nbs/04_media.ipynb #1828a160
def _sha1(data): return hashlib.sha1(data).hexdigest()

def add_media_file(folder, data, fname):
    "Write `data` into `folder` under (normalized) `fname` without clobbering different content; returns the name used"
    folder = Path(folder)
    folder.mkdir(parents=True, exist_ok=True)
    fname = norm_fname(fname)
    csum = _sha1(data)
    p = folder/fname
    if p.exists() and _sha1(p.read_bytes())==csum: return fname
    if fname.lower()!=fname: return add_media_file(folder, data, fname.lower())
    if p.exists(): fname = _hash_name(fname, csum)
    (folder/fname).write_bytes(data)
    return fname

# %% ../nbs/04_media.ipynb #6f4db0c0
MEDIA_SCHEMA = r"""
CREATE TABLE media (
  fname text NOT NULL PRIMARY KEY,
  csum text,            -- NULL: deleted, deletion pending upload
  mtime int NOT NULL,   -- 0 if deleted
  dirty int NOT NULL
) without rowid;
CREATE INDEX idx_media_dirty ON media (dirty) WHERE dirty=1;
CREATE TABLE meta (dirMod int, lastUsn int);
INSERT INTO meta VALUES (0, 0);
"""

class Media:
    "A collection's media folder plus the db tracking its sync state"
    def __init__(self, folder, db_path):
        self.folder = Path(folder)
        self.folder.mkdir(parents=True, exist_ok=True)
        self.con = connect(db_path)
        if not self.con.execute("select 1 from sqlite_master where name='media'").fetchone(): self.con.execute(MEDIA_SCHEMA)
    def close(self): self.con.close()
    def __enter__(self): return self
    def __exit__(self, *args): self.close()
    def entry(self, fname):
        "(csum, mtime, dirty) for `fname`, or None"
        return self.con.execute('select csum, mtime, dirty from media where fname=?', (fname,)).fetchone()
    def set_entry(self, fname, csum, mtime, dirty):
        self.con.execute('insert or replace into media values (?,?,?,?)', (fname, csum, mtime, int(dirty)))
    def meta(self):
        "(dirMod, lastUsn)"
        return self.con.execute('select dirMod, lastUsn from meta').fetchone()
    def set_meta(self, dirmod, last_usn): self.con.execute('update meta set dirMod=?, lastUsn=?', (dirmod, last_usn))
    def count(self): return self.con.execute('select count(*) from media where csum is not null').fetchone()[0]
    def pending(self, limit):
        "Entries awaiting upload, as [(fname, csum, mtime)] with csum None for deletions"
        return self.con.execute('select fname, csum, mtime from media where dirty=1 limit ?', (limit,)).fetchall()
    def force_resync(self):
        "Clear all sync state, so the next sync re-lists everything against the server"
        self.con.execute('delete from media; update meta set lastUsn=0, dirMod=0')

# %% ../nbs/04_media.ipynb #8f88bfe7
MAX_FILE_SIZE = 100*1024*1024

def _mtime_ms(p): return int(p.stat().st_mtime*1000)
def _mtime_s(p): return int(p.stat().st_mtime)

def _syncable_fname(fname):
    "The NFC form of `fname` if sync can use it, else None"
    nfc = unicodedata.normalize('NFC', fname)
    if norm_fname(nfc)!=nfc or _NONSYNCABLE.match(nfc): return None
    if fname!=nfc and sys.platform!='darwin': return None    # only macOS serves NFD names for NFC paths
    return nfc

@patch
def _register_changes(self:Media):
    "Reconcile the db with the folder: new/changed files become dirty entries, missing files deletion tombstones"
    dirmod = _mtime_ms(self.folder)
    dirmod0,last_usn = self.meta()
    if dirmod==dirmod0: return
    self.con.execute('BEGIN IMMEDIATE')
    try:
        mtimes = dict(self.con.execute('select fname, mtime from media where csum is not null'))
        for p in self.folder.iterdir():
            fname = _syncable_fname(p.name)
            if fname is None or not p.is_file(): continue
            sz = p.stat().st_size
            if not sz or sz>MAX_FILE_SIZE: continue
            prev = mtimes.pop(fname, None)
            mtime = _mtime_s(p)
            if prev==mtime: continue
            csum,cur = _sha1(p.read_bytes()),self.entry(fname)
            dirty = cur[2] if prev is not None and cur and cur[0]==csum else True   # mtime bumped, content unchanged: keep flag
            self.set_entry(fname, csum, mtime, dirty)
        for fname in mtimes: self.set_entry(fname, None, 0, True)                   # in the db, gone from disk
        self.set_meta(dirmod, last_usn)
        self.con.execute('COMMIT')
    except: self.con.execute('ROLLBACK'); raise

# %% ../nbs/04_media.ipynb #72b1edc2
MAX_ZIP_FILES = 25
TARGET_ZIP_BYTES = int(2.5*1024*1024)

def _zip_up(entries):
    "Zip [(fname, data|None)] for upload; None data records a deletion"
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_STORED) as z:
        meta = []
        for i,(fname,data) in enumerate(entries):
            if data is None: meta.append((fname, None))
            else:
                z.writestr(str(i), data)
                meta.append((fname, str(i)))
        z.writestr('_meta', json.dumps(meta))
    return buf.getvalue()

def _unzip_down(zdata):
    "[(fname, data)] from a downloaded zip"
    with zipfile.ZipFile(io.BytesIO(zdata)) as z:
        names = json.loads(z.read('_meta'))
        return [(names[i.filename], z.read(i.filename)) for i in z.infolist() if i.filename!='_meta']

@patch
def _gather_zip(self:Media, entries):
    "[(fname, data|None)] to upload for pending `entries`; None if bad entries were pruned and the batch must be rebuilt"
    bad,out,size = [],[],0
    for fname,csum,_ in entries:
        if size>TARGET_ZIP_BYTES: break
        if sys.platform=='darwin' and unicodedata.normalize('NFC', fname)!=fname:   # pre-normalization Anki left NFD names in dbs
            bad.append(fname)
            continue
        data = None
        if csum is not None and (self.folder/fname).exists():
            data = (self.folder/fname).read_bytes()
            if not data or len(data)>MAX_FILE_SIZE or norm_fname(fname)!=fname:
                bad.append(fname)
                continue
            size += len(data)
        out.append((fname, data))
    if not bad: return out
    for f in bad: self.con.execute('delete from media where fname=?', (f,))
    return None

# %% ../nbs/04_media.ipynb #4145f907
class MediaSanityFailed(Exception): pass

@patch
def _mjson(self:SyncServer, method, obj=None, data=None):
    "POST to msync/`method`, unwrapping the legacy {data,err} envelope of media replies"
    r = json.loads(self(method, obj, data, prefix='msync'))
    if r.get('err'): raise Exception(f"Media sync: {r['err']}")
    return r['data']

# %% ../nbs/04_media.ipynb #861e2b20
def required_change(local, remote, state):
    "Resolve one server row: sha1s ('' means deleted), `state` in none/clean/dirty -> None, 'download', 'delete', or 'clean'"
    if not local and not remote: return None if state=='none' else 'delete'
    if not remote: return None if state=='dirty' else 'delete'
    if not local: return 'download'
    if local==remote: return 'clean' if state=='dirty' else None
    return 'download'

@patch
def _required_changes(self:Media, batch):
    "Sort server rows into filenames (to_download, to_delete, to_mark_clean)"
    dl,rm,cl = [],[],[]
    for fname,usn,rsum in batch:
        e = self.entry(fname)
        local,state = (e[0] or '', 'dirty' if e[2] else 'clean') if e else ('', 'none')
        c = required_change(local, rsum, state)
        if c=='download': dl.append(fname)
        elif c=='delete': rm.append(fname)
        elif c=='clean': cl.append(fname)
    return dl,rm,cl

# %% ../nbs/04_media.ipynb #bc674cc2
@patch
def _trash_files(self:Media, fnames):
    "Move `fnames` from the media folder into a sibling media.trash folder"
    if not fnames: return
    trash = self.folder.with_name('media.trash')
    trash.mkdir(exist_ok=True)
    for f in fnames:
        p = self.folder/f
        if p.exists(): p.replace(trash/f)

@patch
def _add_from_server(self:Media, fname, data):
    "Write a downloaded file; returns the db rows to record, as (fname, csum, mtime, dirty) tuples"
    if norm_fname(fname)==fname:
        p = self.folder/fname
        p.write_bytes(data)
        return [(fname, _sha1(data), _mtime_s(p), False)]
    used = add_media_file(self.folder, data, fname)                    # a pre-normalization name: store it corrected
    return [(fname, None, 0, True), (used, _sha1(data), _mtime_s(self.folder/used), True)]

# %% ../nbs/04_media.ipynb #ef83de16
@patch
def sync(self:Media, srv, server_usn=None):
    "Sync the media folder with `srv`: pull server changes, push local ones, then verify counts"
    self._register_changes()
    if server_usn is None: server_usn = srv._mjson('begin', dict(v=CLIENT_VER))['usn']
    acted = False
    if self.meta()[1]!=server_usn:
        self._fetch_changes(srv)
        acted = True
    if self.pending(1):
        self._send_changes(srv)
        acted = True
    if acted: self._finalize(srv)

@patch
def _fetch_changes(self:Media, srv):
    while True:
        batch = srv._mjson('mediaChanges', dict(lastUsn=self.meta()[1]))
        if not batch: return
        dl,rm,cl = self._required_changes(batch)
        self._trash_files(rm)
        added = []
        for chunk in chunked(dl, MAX_ZIP_FILES):
            zdata = srv('downloadFiles', dict(files=chunk), prefix='msync')
            for fname,data in _unzip_down(zdata): added += self._add_from_server(fname, data)
        self.con.execute('BEGIN IMMEDIATE')
        try:
            for f in cl: self.con.execute('update media set dirty=0 where fname=?', (f,))
            for f in rm: self.con.execute('delete from media where fname=?', (f,))
            for e in added: self.set_entry(*e)
            self.set_meta(_mtime_ms(self.folder), batch[-1][1])
            self.con.execute('COMMIT')
        except: self.con.execute('ROLLBACK'); raise

@patch
def _send_changes(self:Media, srv):
    while True:
        entries = self.pending(MAX_ZIP_FILES)
        if not entries: return
        batch = self._gather_zip(entries)
        if batch is None: continue                       # unuploadable entries were pruned; rebuild the batch
        processed,current_usn = srv._mjson('uploadChanges', data=_zip_up(batch))
        self.con.execute('BEGIN IMMEDIATE')
        try:
            done = [f for f,_ in batch[:processed]]
            for f in done: self.con.execute('update media set dirty=0 where fname=?', (f,))
            dirmod,last_usn = self.meta()
            # adopt the server's usn only if we produced it all; otherwise another client also uploaded, and the next fetch must see their changes
            if last_usn+len(done)==current_usn: self.set_meta(dirmod, current_usn)
            self.con.execute('COMMIT')
        except: self.con.execute('ROLLBACK'); raise

@patch
def _finalize(self:Media, srv):
    if srv._mjson('mediaSanity', dict(local=self.count()))!='OK':
        self.force_resync()
        raise MediaSanityFailed()

# %% ../nbs/04_media.ipynb #83ecb705
@patch
def media(self:Collection):
    "This collection's `Media`; close it after use (or use as a context manager)"
    return Media(self.path.with_suffix('.media'), self.path.with_suffix('.mdb'))

@patch
def add_media(self:Collection, file, fname=None):
    "Copy `file` (a path, or bytes with `fname`) into the media folder; returns the name to reference in note fields"
    if fname is None: fname = Path(file).name
    data = file if isinstance(file, bytes) else Path(file).read_bytes()
    return add_media_file(self.path.with_suffix('.media'), data, fname)

@patch
def sync_media(self:Collection, srv=None):
    "Media-sync with `srv` (default: the saved auth from a previous `sync`)"
    if srv is None: srv = self.load_auth()
    if srv is None: raise ValueError('No saved auth; sync() first')
    with self.media() as m: m.sync(srv)
