"""Reading and writing Anki's schema-18 sqlite collections, no Anki required

Docs: https://AnswerDotAI.github.io/fastanki/schema.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_schema.ipynb.

# %% auto #0
__all__ = ['STOCK', 'SCHEMA', 'CARD_CSS', 'CLOZE_CSS', 'LATEX_PRE', 'LATEX_POST', 'DEFAULT_CONFIG', 'unicase', 'connect',
           'now_ms', 'day_offset', 'creation_stamp', 'ts_id', 'field_cfg', 'template_cfg', 'notetype_cfg',
           'add_notetype', 'add_basic', 'add_cloze', 'default_deck_config', 'deck_common', 'deck_kind',
           'create_collection']

# %% ../nbs/00_schema.ipynb #b6750338
import apsw, time, random, json
from apsw import bestpractice
from fastcore.utils import *
from ._proto import notetypes_pb2, decks_pb2, deck_config_pb2
STOCK = notetypes_pb2.StockNotetype.OriginalStockKind

# %% ../nbs/00_schema.ipynb #29288d60
SCHEMA = r"""
CREATE TABLE cards (
  id integer PRIMARY KEY,
  nid integer NOT NULL,
  did integer NOT NULL,
  ord integer NOT NULL,
  mod integer NOT NULL,
  usn integer NOT NULL,
  type integer NOT NULL,
  queue integer NOT NULL,
  due integer NOT NULL,
  ivl integer NOT NULL,
  factor integer NOT NULL,
  reps integer NOT NULL,
  lapses integer NOT NULL,
  left integer NOT NULL,
  odue integer NOT NULL,
  odid integer NOT NULL,
  flags integer NOT NULL,
  data text NOT NULL
);
CREATE TABLE col (
  id integer PRIMARY KEY,
  crt integer NOT NULL,
  mod integer NOT NULL,
  scm integer NOT NULL,
  ver integer NOT NULL,
  dty integer NOT NULL,
  usn integer NOT NULL,
  ls integer NOT NULL,
  conf text NOT NULL,
  models text NOT NULL,
  decks text NOT NULL,
  dconf text NOT NULL,
  tags text NOT NULL
);
CREATE TABLE config (
  KEY text NOT NULL PRIMARY KEY,
  usn integer NOT NULL,
  mtime_secs integer NOT NULL,
  val blob NOT NULL
) without rowid;
CREATE TABLE deck_config (
  id integer PRIMARY KEY NOT NULL,
  name text NOT NULL COLLATE unicase,
  mtime_secs integer NOT NULL,
  usn integer NOT NULL,
  config blob NOT NULL
);
CREATE TABLE decks (
  id integer PRIMARY KEY NOT NULL,
  name text NOT NULL COLLATE unicase,
  mtime_secs integer NOT NULL,
  usn integer NOT NULL,
  common blob NOT NULL,
  kind blob NOT NULL
);
CREATE TABLE fields (
  ntid integer NOT NULL,
  ord integer NOT NULL,
  name text NOT NULL COLLATE unicase,
  config blob NOT NULL,
  PRIMARY KEY (ntid, ord)
) without rowid;
CREATE TABLE graves (
  oid integer NOT NULL,
  type integer NOT NULL,
  usn integer NOT NULL,
  PRIMARY KEY (oid, type)
) WITHOUT ROWID;
CREATE TABLE notes (
  id integer PRIMARY KEY,
  guid text NOT NULL,
  mid integer NOT NULL,
  mod integer NOT NULL,
  usn integer NOT NULL,
  tags text NOT NULL,
  flds text NOT NULL,
  -- The use of type integer for sfld is deliberate, because it means that integer values in this
  -- field will sort numerically.
  sfld integer NOT NULL,
  csum integer NOT NULL,
  flags integer NOT NULL,
  data text NOT NULL
);
CREATE TABLE notetypes (
  id integer NOT NULL PRIMARY KEY,
  name text NOT NULL COLLATE unicase,
  mtime_secs integer NOT NULL,
  usn integer NOT NULL,
  config blob NOT NULL
);
CREATE TABLE revlog (
  id integer PRIMARY KEY,
  cid integer NOT NULL,
  usn integer NOT NULL,
  ease integer NOT NULL,
  ivl integer NOT NULL,
  lastIvl integer NOT NULL,
  factor integer NOT NULL,
  time integer NOT NULL,
  type integer NOT NULL
);
CREATE TABLE tags (
  tag text NOT NULL PRIMARY KEY COLLATE unicase,
  usn integer NOT NULL,
  collapsed boolean NOT NULL,
  config blob NULL
) without rowid;
CREATE TABLE templates (
  ntid integer NOT NULL,
  ord integer NOT NULL,
  name text NOT NULL COLLATE unicase,
  mtime_secs integer NOT NULL,
  usn integer NOT NULL,
  config blob NOT NULL,
  PRIMARY KEY (ntid, ord)
) without rowid;
CREATE INDEX idx_cards_odid ON cards (odid)
WHERE odid != 0;
CREATE UNIQUE INDEX idx_decks_name ON decks (name);
CREATE UNIQUE INDEX idx_fields_name_ntid ON fields (name, ntid);
CREATE INDEX idx_graves_pending ON graves (usn);
CREATE INDEX idx_notes_mid ON notes (mid);
CREATE UNIQUE INDEX idx_notetypes_name ON notetypes (name);
CREATE INDEX idx_notetypes_usn ON notetypes (usn);
CREATE UNIQUE INDEX idx_templates_name_ntid ON templates (name, ntid);
CREATE INDEX idx_templates_usn ON templates (usn);
CREATE INDEX ix_cards_nid ON cards (nid);
CREATE INDEX ix_cards_sched ON cards (did, queue, due);
CREATE INDEX ix_cards_usn ON cards (usn);
CREATE INDEX ix_notes_csum ON notes (csum);
CREATE INDEX ix_notes_usn ON notes (usn);
CREATE INDEX ix_revlog_cid ON revlog (cid);
CREATE INDEX ix_revlog_usn ON revlog (usn);
"""

# %% ../nbs/00_schema.ipynb #25b5d006
def unicase(a:str, b:str):
    "sqlite collation function matching Anki's case-insensitive `unicase`"
    a,b = a.casefold(),b.casefold()
    return -1 if a<b else (1 if a>b else 0)

def connect(path):
    "Connect to collection sqlite file at `path`, with Anki's `unicase` collation and apsw best practices"
    con = apsw.Connection(str(path))
    bestpractice.connection_busy_timeout(con)  # first, so the WAL pragma and every later write wait for the lock rather than erroring
    bestpractice.connection_wal(con)           # WAL journal mode
    bestpractice.connection_dqs(con)           # double quotes are identifiers only; SQL string literals must use single quotes
    con.create_collation('unicase', unicase)
    return con

# %% ../nbs/00_schema.ipynb #164a8cae
def now_ms(): return int(time.time()*1000)

def day_offset():
    "Minutes west of UTC, Anki's `creationOffset` (eg Australia at +10h is -600)"
    return -int(time.localtime().tm_gmtoff//60)

def creation_stamp():
    "Collection creation time: the most recent 4am in the local timezone"
    t = time.localtime()
    four_am = int(time.mktime((t.tm_year, t.tm_mon, t.tm_mday, 4, 0, 0, 0, 0, -1)))
    return four_am if four_am<=int(time.time()) else four_am-86400

# %% ../nbs/00_schema.ipynb #46cfe841
def ts_id(con, table):
    "New timestamp-based id for `table`: now in ms, or 1 past the max existing id"
    mx = con.execute(f'select max(id) from {table}').fetchone()[0]
    return max(now_ms(), (mx or 0)+1)

# %% ../nbs/00_schema.ipynb #7f14e4de
CARD_CSS = '.card {\n    font-family: arial;\n    font-size: 20px;\n    line-height: 1.5;\n    text-align: center;\n    color: black;\n    background-color: white;\n}\n'
CLOZE_CSS = CARD_CSS + '.cloze {\n    font-weight: bold;\n    color: blue;\n}\n.nightMode .cloze {\n    color: lightblue;\n}\n'
LATEX_PRE = '\\documentclass[12pt]{article}\n\\special{papersize=3in,5in}\n\\usepackage[utf8]{inputenc}\n\\usepackage{amssymb,amsmath}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0in}\n\\begin{document}\n'
LATEX_POST = '\\end{document}'

# %% ../nbs/00_schema.ipynb #b6d49783
def field_cfg(
    tag=None, # Cloze field role marker
    prevent_deletion=False, # Protect the field from deletion in Anki's UI
):
    c = notetypes_pb2.Notetype.Field.Config(font_name='Arial', font_size=20, id=random.getrandbits(63))
    if tag is not None: c.tag = tag
    if prevent_deletion: c.prevent_deletion = True
    return c.SerializeToString()

def template_cfg(q, a):
    c = notetypes_pb2.Notetype.Template.Config(q_format=q, a_format=a, id=random.getrandbits(63))
    return c.SerializeToString()

def notetype_cfg(
    kind=0, # 0 normal, 1 cloze
    stock=0, # original_stock_kind, for Anki's "restore to default" feature
    reqs=None, # [(card_ord, 'any'|'all', [field_ords])] card generation requirements
    css=CARD_CSS,
):
    c = notetypes_pb2.Notetype.Config(kind=kind, css=css, latex_pre=LATEX_PRE, latex_post=LATEX_POST, original_stock_kind=stock)
    for ord_,rkind,fords in reqs or []:
        r = c.reqs.add()
        r.card_ord,r.kind = ord_, notetypes_pb2.Notetype.Config.CardRequirement.Kind.Value(f'KIND_{rkind.upper()}')
        r.field_ords.extend(fords)
    return c.SerializeToString()

# %% ../nbs/00_schema.ipynb #7ba75f8b
def add_notetype(con, name, flds, tmpls, cfg):
    "Insert a notetype with `flds` [(name, config_bytes)] and `tmpls` [(name, config_bytes)], returning its id"
    ntid = ts_id(con, 'notetypes')
    con.execute('insert into notetypes values (?,?,?,?,?)', (ntid, name, 0, 0, cfg))
    con.executemany('insert into fields values (?,?,?,?)', [(ntid, i, n, c) for i,(n,c) in enumerate(flds)])
    con.executemany('insert into templates values (?,?,?,?,?,?)', [(ntid, i, n, 0, 0, c) for i,(n,c) in enumerate(tmpls)])
    return ntid

def add_basic(con):
    tmpl = template_cfg('{{Front}}', '{{FrontSide}}\n\n<hr id=answer>\n\n{{Back}}')
    cfg = notetype_cfg(stock=STOCK.Value('ORIGINAL_STOCK_KIND_BASIC'), reqs=[(0,'any',[0])])
    return add_notetype(con, 'Basic', [('Front',field_cfg()),('Back',field_cfg())], [('Card 1',tmpl)], cfg)

def add_cloze(con):
    tmpl = template_cfg('{{cloze:Text}}', '{{cloze:Text}}<br>\n{{Back Extra}}')
    flds = [('Text',field_cfg(tag=0, prevent_deletion=True)),('Back Extra',field_cfg(tag=1))]
    cfg = notetype_cfg(kind=1, css=CLOZE_CSS, stock=STOCK.Value('ORIGINAL_STOCK_KIND_CLOZE'), reqs=[(0,'any',[0])])
    return add_notetype(con, 'Cloze', flds, [('Cloze',tmpl)], cfg)

# %% ../nbs/00_schema.ipynb #8db3fd52
DEFAULT_CONFIG = dict(activeDecks=[1], addToCur=True, collapseTime=1200, curDeck=1, dayLearnFirst=False,
    dueCounts=True, estTimes=True, newSpread=0, nextPos=1, sched2021=True, schedVer=2,
    sortBackwards=False, sortType='noteFld', timeLim=0)

def default_deck_config():
    c = deck_config_pb2.DeckConfig.Config(learn_steps=[1.0,10.0], relearn_steps=[10.0],
        easy_days_percentages=[1.0]*7, new_per_day=20, reviews_per_day=200, initial_ease=2.5,
        easy_multiplier=1.3, hard_multiplier=1.2, interval_multiplier=1.0, maximum_review_interval=36500,
        minimum_lapse_interval=1, graduating_interval_good=1, graduating_interval_easy=4,
        leech_action=deck_config_pb2.DeckConfig.Config.LEECH_ACTION_TAG_ONLY, leech_threshold=8,
        cap_answer_time_to_secs=60, desired_retention=0.9, historical_retention=0.9, wait_for_audio=True)
    return c.SerializeToString()

def deck_common(): return decks_pb2.Deck.Common(study_collapsed=True, browser_collapsed=True).SerializeToString()

def deck_kind(config_id=1):
    return decks_pb2.Deck.KindContainer(normal=decks_pb2.Deck.Normal(config_id=config_id)).SerializeToString()

# %% ../nbs/00_schema.ipynb #15379002
def create_collection(path):
    "Create a new empty schema-18 collection at `path`, returning a connection to it"
    path = Path(path)
    assert not path.exists(), f"{path} already exists"
    path.parent.mkdir(parents=True, exist_ok=True)
    con = connect(path)
    con.execute(SCHEMA)
    now = now_ms()
    con.execute("insert into col values (1,?,0,?,18,0,0,0,'','','','','')", (creation_stamp(), now))
    for k,v in DEFAULT_CONFIG.items(): con.execute('insert into config values (?,0,0,?)', (k, json.dumps(v).encode()))
    con.execute('insert into config values (?,0,0,?)', ('creationOffset', json.dumps(day_offset()).encode()))
    con.execute("insert into deck_config values (1,'Default',0,0,?)", (default_deck_config(),))
    con.execute("insert into decks values (1,'Default',0,0,?,?)", (deck_common(), deck_kind()))
    basic = add_basic(con); add_cloze(con)
    con.execute('insert into config values (?,-1,?,?)', ('curModel', now//1000, json.dumps(basic).encode()))
    return con
